services:
- docker
env:
global:
- secure: "gck1LMZ51VVPSeu3vtw3o9RbczFO+ZMSp79A6/aUmlodKzuYmZRmZu25PqfeCAmLyNdsJFl8tZDsjLRTSrKv0yOj4NY/mWaJN7VIkBSwxM7cmyAqGhFbw2lWeeM0EM3Vf8xKNHYd3jCW/ifczAETMfY+XWz+IsKfAW/thARB0tzD6VdNDFykiiVBjzqh15aHzZOZDl8q+X1pv06lqSrjiqeZEG7rC8RRhGMTf8/wm4ikdWDUL8xGgQ/CP8Wj8FvV+5iOqkGePbBQd/SMgvDgbLN6LlPJNUvzxnLyMI5Q9yYxcUvorHIxJ/j/59FxKJ+lPlvxgMjjejG12UajwUVoT52GmS4gmdl0CpHVnlr3pTca1FNu2kooPeydx1CBDPyHZLtY5x4udflLkZUV2Z6hbc0TMICJB2CjBlHGH8Ob11lvTtGRm4Mb2k3KliQTaCSt4r90K+SKFoCyFc13MgCmAmClnIhB/qXadr29AeyZfqqqvcGdXHdce0ja84nZVZeM80KuhW+DjynB7BXwN8jvtckC66xrH95myN9cdGuZkXw1t07v3pxgUupjs/AX/VuVnSiptt48AYGi1rniFJBy28kTORHM7Ij4kRY5E/CDkpltdIu2kyoCBGw4FP6O6/xLsIiz2Pw1hmedEReUqwLFI25fWva4rKr2JjZfbVtYgJg="
- secure: "FqkNo9Rwe2SwBiwEskjBnVnnvegrHv1zQZO0T0qoGxgsYRBEWoL2jztVEsE2noDsy4CG7CsonCuidoA/xiULh9GYgptXlovx8KuI8mAKhVtNzFY22qerWvZle/1oEE/0DeQX1kvDJ4BsLR4X+jKAwFGOgAdCu2ndbetFk+kSxf11FnsHn+zMeedYieOOz042B4HHwN2LILcsxBLJG4JYH+IXfb9CF9u+07eo/s+0xD4G1T2aKE38IbrsCHbAGbaBzHsz04e+BvWc/4vtOUcWCs6BPeTQdFEKW1woJk0EuG3d21b4xha7q/WXKJYd4ooPgAMAF0X7P9QvZk58mom8HzallIgETK+BryHNvW7XC4LuKbmY6YmORHc8XA8le+m6gFnawiqwD/murzqQiA9srmQWJJRi+pWY4garZdOb2PNP3WExNRoMOiIVz/sATGdYLksmNCQWwS+hZP3MNZn3aw/hAkjPjr+gOG/JfDFD5vJsVmjk66076vYkHg4wkg50Ky6lSMwM15Rv8TTINwz7/jETbG9BEbAU7J6nqqrC4+tAY7YLra8z429QJ4AJqA9SrPiuDo/NaKmY1DSqfwNtXbdk7B3Tl1SVRLB6qFvLBGjz4ikezekOVZqcM1LDmQBmOUuoJIrQOaKZEIbQw8YN9jGz8qfVU07tn9is8n8/tkE="
script:
- export SAVE=$PWD
- docker build -t ubuhphctr .
- sudo ./docker-slim build --continue-after probe --http-probe ubuhphctr
before_deploy:
- cd
- wget `curl -s https://api.github.com/repos/appc/docker2aci/releases | grep browser_download_url
  | head -n 1 | cut -d '"' -f 4` -O d2a.tar.gz
- tar -zxf d2a.tar.gz && rm d2a.tar.gz && d2a=`ls | grep "docker2aci*"` && d2a=`basename
  $d2a` && alias d2a='${PWD}/${d2a}/docker2aci'
- docker save -o ubuhphctr.slim.tar ubuhphctr.slim
- "${PWD}/${d2a}/docker2aci ubuhphctr.slim.tar"
- xz -9 -c ubuhphctr.slim.tar > ubuhphctr.slim.tar.xz
- docker login -u $quaylogin -p $quaypsw quay.io
- docker tag ${cnt}${slim} quay.io/natostanco/$cnt
- docker push quay.io/natostanco/$cnt
deploy:
  provider: releases
  api_key:
    secure: Q0trcCSflN99DkUzYsqKdAXmLJrbSM8YChi4CTiiPX8YbBrKM2ZEeYPYcwBSmqpxLsTLPG+/+Rgo7klP627ysiUFWLq6IZgW0+A6ux+3YA72TV2kpr3NNYwSLXOVpGP63kA7AxiLe6AHOAE6S+1vfgRBfq0aH4fX0YMeLhR43poSaCFPb8OTLURwFx8wzLLdTNW6hdLpSakAhyOUwSABNx2gk1px1/Xx0oMex2WFLppGvtgmaH2hMwjkOj2RF4yPVW865UNI7JYAqgtzKaGJqhSrhREaLzdwxryrjLUoPCturoqrhUQIfweil1X10wmtF/QC0bu18BkDpvzqaTq7O8QaoqMt/0YD2kaTQovcSjNGaadzVSM7uNORXht3IfFJ4CwflemO7JQ0NFOW5fjABSQO8lSasTUfQDkhwCoRWY+uTd+5yQkFDltb+Wu4ltsqFTRndZVS/KNdZrRfmfzYFavr6tejTuJDGHp5Zk4fhsLm2mO5UnqbOmTk7g/BmE8LUbDmP1zC2WfgDK8BaX47c+zc2sfbinFdmd2pff78gVV27dwJ9VMXVGAtaaCF6C5Vzy/b33IonOO+llbN9JqyiwgIOqlI0JS9rMUncI7koHXaeqHqv+V6y3CCNYRU4nX+ReF8t2ILcK1kzd3St32Vjp30e7pzoqpDjvp2xhEXcZI=
  file:
  - ubuhphctr.slim.tar.xz 
  - ubuhphctr.slim-latest.aci 
  skip_cleanup: true
  on:
    tags: true
